# Database
spring:
  datasource:
    url: jdbc:h2:mem:leaf;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop

# Logging
logging:
  level.: info
  level.org.hibernate: debug